# Generated by Django 3.0.6 on 2020-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('dbAbbreviation', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
