# Generated by Django 3.0.6 on 2020-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
