# Generated by Django 3.0.6 on 2020-05-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_auto_20200527_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='dbAbbreviation',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='image',
            field=models.ImageField(blank=True, default='static/defaultDBImage.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
