# Generated by Django 3.0.6 on 2020-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_auto_20200531_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='image',
            field=models.ImageField(blank=True, default='defaultDBImage.png', null=True, upload_to=''),
        ),
    ]
