# Generated by Django 3.0.6 on 2020-06-03 14:03

import databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0006_auto_20200603_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='image',
            field=models.ImageField(blank=True, default='/Users/Clemens/Desktop/django_database/django_simfuel/src/static/images/databaseImages/defaultDBImage.png', null=True, upload_to=databases.models.content_file_name),
        ),
    ]
