# Generated by Django 3.0.6 on 2020-06-03 15:08

import databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0012_auto_20200603_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='image',
            field=models.ImageField(blank=True, default='defaultDBImage.png', null=True, upload_to=databases.models.content_file_name),
        ),
    ]
