# Generated by Django 3.0.6 on 2020-06-03 15:34

import databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0017_auto_20200603_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='image',
            field=models.FileField(upload_to=databases.models.content_file_name),
        ),
    ]
