# Generated by Django 3.0.6 on 2020-05-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchKey', models.CharField(max_length=120)),
                ('user', models.CharField(max_length=120)),
                ('selectedDB', models.CharField(max_length=120)),
                ('search', models.CharField(max_length=120)),
            ],
        ),
    ]
