# Generated by Django 3.0.6 on 2020-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200524_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searchDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
