# Generated by Django 3.0.6 on 2020-05-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200524_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='searchDate',
        ),
    ]
