# Generated by Django 3.0.6 on 2020-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_search_searchdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='searchDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
