# Generated by Django 3.0.6 on 2020-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20200524_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='selectedDB',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
