# Generated by Django 3.0.6 on 2020-05-26 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200525_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='searchDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
