# Generated by Django 3.0.6 on 2020-06-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='modified',
        ),
        migrations.AddField(
            model_name='notebook',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
