# Generated by Django 3.0.6 on 2020-06-03 13:20

from django.db import migrations, models
import notebooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_auto_20200602_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='file',
            field=models.FileField(default='/Users/Clemens/Desktop/django_database/django_simfuel/src/static/notebooks/Test.ipynb', upload_to=notebooks.models.content_file_name),
        ),
    ]
