# Generated by Django 3.0.6 on 2020-06-03 19:49

import django.core.validators
from django.db import migrations, models
import notebooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0015_auto_20200603_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='file',
            field=models.FileField(blank=True, upload_to=notebooks.models.content_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ipynb'])]),
        ),
    ]
