# Generated by Django 3.0.6 on 2020-06-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0017_auto_20200603_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
