# Generated by Django 3.0.6 on 2020-05-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200527_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=models.CharField(choices=[('a', 'CRC World Fuel Survey')], max_length=1),
        ),
    ]
