# Generated by Django 3.0.6 on 2020-05-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200527_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=models.CharField(max_length=100),
        ),
    ]
