# Generated by Django 3.0.6 on 2020-05-28 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200528_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('a', 'CRC World Fuel Survey'), ('b', 'CRC World Fuel Survey')], max_length=2), size=None),
        ),
    ]
