# Generated by Django 3.0.6 on 2020-05-28 19:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200528_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None),
        ),
    ]
