# Generated by Django 3.0.6 on 2020-05-28 19:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200528_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'CRC World Fuel Survey'), ('b', 'new')], max_length=3),
        ),
    ]
