# Generated by Django 3.0.6 on 2020-05-28 20:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200528_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CRC World Fuel Survey', 'CRC World Fuel Survey'), ('b', 'new')], max_length=23),
        ),
    ]
