# Generated by Django 3.0.6 on 2020-05-29 20:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CRCfuels', 'CRC World Fuel Survey'), ('Brazilfuel', 'Brazil fuels')], max_length=19),
        ),
    ]
