# Generated by Django 3.0.6 on 2020-05-31 19:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200529_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CRCfuels', 'CRC World Fuel Survey'), ('Brazilfuel', 'Brazil fuels'), ('new', 'new'), ('abc', 'abc')], max_length=27),
        ),
    ]
