# Generated by Django 3.0.6 on 2020-05-31 20:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200531_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CRCfuels', 'CRC World Fuel Survey'), ('Brazilfuel', 'Brazil fuels'), ('new', 'new'), ('abc', 'abc'), ('abcnew', 'abcnew'), ('abad', 'abac')], max_length=39),
        ),
    ]
