# Generated by Django 3.0.6 on 2020-05-31 20:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200531_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Brazil fuels'), (1, 'CRC World Fuel Survey')], max_length=3),
        ),
    ]
