# Generated by Django 3.0.6 on 2020-06-02 19:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200531_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('j', 'fff')], max_length=10),
        ),
    ]
