# Generated by Django 3.0.6 on 2020-06-03 14:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200603_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('new', 'new')], max_length=100),
        ),
    ]
