# Generated by Django 3.0.6 on 2020-06-03 15:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20200603_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'a'), ('1', '5'), ('7', '7')], max_length=100),
        ),
    ]
