# Generated by Django 3.0.6 on 2020-06-03 15:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20200603_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'ab')], max_length=100),
        ),
    ]
