# Generated by Django 3.0.6 on 2020-06-03 16:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20200603_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('5', '5'), ('a', 'ab'), ('gasdd', 'ga'), ('zzz', 'zzz'), ('la', 'lad')], max_length=100),
        ),
    ]
