# Generated by Django 3.0.6 on 2020-06-03 16:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20200603_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='allowedDB',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('db1', 'db1'), ('dbdefault', 'dbdefault')], max_length=100),
        ),
    ]
